# Generated by Django 6.0 on 2025-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='overtime',
            new_name='overtime_hours',
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.FloatField(editable=False),
        ),
    ]
