# Generated by Django 6.0 on 2025-12-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_overtime_payroll_overtime_hours_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveRequests',
            new_name='LeaveRequest',
        ),
    ]
