# Generated by Django 6.0 on 2025-12-17 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_leaverequests_leaverequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='overtime_hours',
            new_name='overtime',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_rate',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
