# Generated by Django 6.0 on 2025-12-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_overtime_hours_payroll_overtime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveRequest',
            new_name='LeaveRequests',
        ),
    ]
