# Generated by Django 6.0 on 2025-12-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_leaverequest_leaverequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessions',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingsessions',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
