# Generated by Django 6.0 on 2025-12-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_deliveryroute_deliverytracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.FloatField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.generatedreport')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.FloatField()),
                ('total_expenses', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.generatedreport')),
            ],
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reporttype'),
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField()),
                ('total_sales', models.FloatField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.generatedreport')),
            ],
        ),
    ]
